---
title: "AFLW Fantasy Top Coaches"
execute:
  echo: false
---

```{r}
#| message: false

library(modules)
library(arrow)
library(reactable)
library(dplyr)
library(tidyr)
library(purrr)
library(scales)
library(htmltools)

source("../../parameters.R")
linked_icons <- use("../../modules/linked_icons.R")

ranking_data <- read_parquet("https://github.com/bit-in-that/data-automation/raw/main/aflw_fantasy/data/processed/ranking_data.parquet") |> 
  mutate( 
    img_url = paste0("https://aflwfantasy.afl/media/avatars/user/", userId, ".png?v=1"),
    fantasy_url = paste0("https://aflwfantasy.afl/user/team/", parameters$round_number,"/", userId),
    value_rank = rank(-teamValue, ties.method = "first")
  ) 

content_creators_ranks <- read_parquet("https://github.com/bit-in-that/data-automation/raw/main/aflw_fantasy/data/processed/content_creators_ranks_aflw.parquet") |>
mutate( 
    img_url = paste0("https://aflwfantasy.afl/media/avatars/user/", user_id, ".png?v=1"),
    fantasy_url = paste0("https://aflwfantasy.afl/user/team/", parameters$round_number,"/", team_id_2023)
  ) |> 
  select("team_name", "overall_rank", "total_points", "roundRank", "roundPoints", "name", "individual_url", "organisation", "twitter", "facebook", "website", "YouTube", "spotify", "primary_url", "img_url", "fantasy_url", "user_id") |> 
  arrange(overall_rank)


```

*The data below is as at round `r parameters$round_number` of the 2023 AFLW season.*



# {{< fa gauge-high >}} Overall Rank Pace

```{r}

rank_pace <- tibble(
  overallRank = c(1, 100, 1000 * (1:10)),
  rank_label = c("FirstðŸš—", "100ðŸ§¢", number(1000 * (1:10), big.mark = ","))
) |> 
  mutate(
    ranks_df = map(overallRank, ~ {
      ranking_data |> 
        slice(1:.x) |> 
        select(totalPoints, teamValue) |> 
        summarise(
          total_points = min(totalPoints),
          average_value = mean(teamValue),
          min_value = min(teamValue),
          max_value = max(teamValue),
          max_value = max(teamValue)
        )
      })
  ) |> 
  unnest(ranks_df)

rank_pace |> 
  reactable(
    columns = list(
      overallRank = colDef(
        name = "Rank", 
        width = 80, 
        sticky = "left",
        cell = function(cell_value, row_index, column_name) {
          rank_pace[["rank_label"]][[row_index]]
        }),
      total_points = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      average_value = colDef(name = "Average", width = 100, cell = \(cell_value) paste0("$", round(cell_value/1000000, 3), "m")),
      min_value = colDef(name = "Min", width = 100, cell = \(cell_value) paste0("$", round(cell_value/1000000, 3), "m")),
      max_value = colDef(name = "Max", width = 100, cell = \(cell_value) paste0("$", round(cell_value/1000000, 3), "m")),
      rank_label = colDef(show = FALSE)
    ),
    columnGroups = list(
      colGroup(name = "Team Value", columns = c("average_value", "min_value", "max_value"))
      ),
    filterable = TRUE,
    pagination = FALSE
  )

```


# {{< fa bullhorn >}} High Profile

Check out the track records of podcast hosts and other high profile coaches below.

```{r}
content_creators_ranks |> 
  select(-user_id) |> 
  reactable(
    columns = list(
      team_name = colDef(
        name = "Fantasy Team",
        sticky = "left",
        cell = function(cell_value, row_index, column_name) {
          img_url <- content_creators_ranks[["img_url"]][[row_index]]
          fantasy_url <- content_creators_ranks[["fantasy_url"]][[row_index]]
          tags$a(
            tags$img(src = img_url, style = "height: 24px;width: 24px;"),
            " ",
            cell_value,
            href = fantasy_url, 
            target = "_blank"
            )
        },
        width = 200
      ),
      name = colDef(
        name = "Person",
        cell = function(cell_value, row_index, column_name) {
          individual_url <- content_creators_ranks[["individual_url"]][[row_index]]
          tags$a(
            cell_value,
            href = individual_url,
            target = "_blank"
            )
        },
        width = 175
      ),
      organisation = colDef(
        name = "Name",
        cell = function(cell_value, row_index, column_name) {
          primary_url <- content_creators_ranks[["primary_url"]][[row_index]]
          tags$a(
            cell_value,
            href = primary_url,
            target = "_blank"
            )
        },
        width = 200
      ),
      primary_url = colDef(
        name = "Links",
        cell = function(cell_value, row_index, column_name) {
          twitter <- content_creators_ranks[["twitter"]][[row_index]]
          facebook <- content_creators_ranks[["facebook"]][[row_index]]
          website <- content_creators_ranks[["website"]][[row_index]]
          YouTube <- content_creators_ranks[["YouTube"]][[row_index]]
          spotify <- content_creators_ranks[["spotify"]][[row_index]]
          
          tagList(
            if(isFALSE(twitter == "")) linked_icons$linked_twitter_icon(twitter) else NULL,
            if(isFALSE(facebook == "")) linked_icons$linked_facebook_icon(facebook) else NULL,
            if(isFALSE(website == "")) linked_icons$linked_globe_icon(website) else NULL,
            if(isFALSE(YouTube == "")) linked_icons$linked_youtube_icon(YouTube) else NULL,
            if(isFALSE(spotify == "")) linked_icons$linked_spotify_icon(spotify) else NULL
          )
        },
        width = 120
      ),
      overall_rank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      total_points = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      roundRank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      roundPoints = colDef(name = "Points", width = 100, format = colFormat(separators = TRUE)),
      individual_url = colDef(show = FALSE),
      twitter = colDef(show = FALSE),
      facebook = colDef(show = FALSE),
      website = colDef(show = FALSE),
      YouTube = colDef(show = FALSE),
      spotify = colDef(show = FALSE),
      img_url = colDef(show = FALSE),
      fantasy_url = colDef(show = FALSE)
    ),
    columnGroups = list(
      colGroup(name = "Overall", columns = c("overall_rank", "total_points")),
      colGroup(name = paste("Round", parameters$round_number), columns = c("roundRank", "roundPoints")),
      colGroup(name = "Organisation", columns = c("organisation", "twitter", "facebook", "website", "YouTube", "spotify", "primary_url"))
      ),
    filterable = TRUE
  )


```




# {{< fa hat-wizard >}} Highest Performers

::: {.panel-tabset}

## Top 100 Rank ðŸ§¢

```{r}
ranking_data |> 
  filter(
    overallRank %in% 1:100
  ) |> 
  select(teamName, overallRank, totalPoints, roundRank, roundPoints, teamValue, value_rank) |> 
    reactable(
    columns = list(
      teamName = colDef(
        name = "Fantasy Team",
        sticky = "left",
        cell = function(cell_value, row_index, column_name) {
          img_url <- ranking_data[["img_url"]][[row_index]]
          fantasy_url <- ranking_data[["fantasy_url"]][[row_index]]
          tags$a(
            tags$img(src = img_url, style = "height: 24px;width: 24px;"),
            " ",
            cell_value,
            href = fantasy_url, 
            target = "_blank"
            )
        },
        width = 200
      ),
      overallRank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      totalPoints = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      roundRank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      roundPoints = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      teamValue = colDef(name = "Amount", width = 100, cell = \(cell_value) paste0("$", cell_value/1000000, "m")),
      value_rank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE))
    ),
    columnGroups = list(
      colGroup(name = "Overall", columns = c("overallRank", "totalPoints")),
      colGroup(name = paste("Round", parameters$round_number), columns = c("roundRank", "roundPoints")),
      colGroup(name = "Team Value", columns = c("teamValue", "value_rank"))
      ),
    filterable = TRUE
  )


```

## Top 100 Week ðŸˆ


```{r}
round_rank_data <- ranking_data |> 
  filter(
    roundRank %in% 1:100
  ) |> 
  arrange(roundRank)

round_rank_data |> 
  select(teamName, roundRank, roundPoints, overallRank, totalPoints, teamValue, value_rank) |> 
    reactable(
    columns = list(
      teamName = colDef(
        name = "Fantasy Team",
        sticky = "left",
        cell = function(cell_value, row_index, column_name) {
          img_url <- round_rank_data[["img_url"]][[row_index]]
          fantasy_url <- round_rank_data[["fantasy_url"]][[row_index]]
          tags$a(
            tags$img(src = img_url, style = "height: 24px;width: 24px;"),
            " ",
            cell_value,
            href = fantasy_url, 
            target = "_blank"
            )
        },
        width = 200
      ),
      overallRank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      totalPoints = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      roundRank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      roundPoints = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      teamValue = colDef(name = "Amount", width = 100, cell = \(cell_value) paste0("$", cell_value/1000000, "m")),
      value_rank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE))
    ),
    columnGroups = list(
      colGroup(name = "Overall", columns = c("overallRank", "totalPoints")),
      colGroup(name = paste("Round", parameters$round_number), columns = c("roundRank", "roundPoints")),
      colGroup(name = "Team Value", columns = c("teamValue", "value_rank"))
      ),
    filterable = TRUE
  )


```

## Top 100 Value ðŸ¤‘


```{r}
ranking_data |> 
  filter(
    value_rank %in% 1:100
  ) |> 
  arrange(
    value_rank
  ) |> 
  select(teamName, teamValue, value_rank, overallRank, totalPoints, roundRank, roundPoints) |> 
    reactable(
    columns = list(
      teamName = colDef(
        name = "Fantasy Team",
        sticky = "left",
        cell = function(cell_value, row_index, column_name) {
          img_url <- ranking_data[["img_url"]][[row_index]]
          fantasy_url <- ranking_data[["fantasy_url"]][[row_index]]
          tags$a(
            tags$img(src = img_url, style = "height: 24px;width: 24px;"),
            " ",
            cell_value,
            href = fantasy_url, 
            target = "_blank"
            )
        },
        width = 200
      ),
      overallRank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      totalPoints = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      roundRank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE)),
      roundPoints = colDef(name = "Points", width = 75, format = colFormat(separators = TRUE)),
      teamValue = colDef(name = "Amount", width = 100, cell = \(cell_value) paste0("$", cell_value/1000000, "m")),
      value_rank = colDef(name = "Rank", width = 75, format = colFormat(separators = TRUE))
    ),
    columnGroups = list(
      colGroup(name = "Overall", columns = c("overallRank", "totalPoints")),
      colGroup(name = paste("Round", parameters$round_number), columns = c("roundRank", "roundPoints")),
      colGroup(name = "Team Value", columns = c("teamValue", "value_rank"))
      ),
    filterable = TRUE
  )


```


:::
