name: Increment Round Number

on: 
  workflow_dispatch:
  schedule:
    - cron: "50 3 * * 1" # 1:50PM every monday
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3 
        
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'
    
    - name: Install R Dependencies 
      uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 1

    - name: Run Script
      run: |
        source("dev/increment_round.R", echo = TRUE)
      shell: Rscript {0}
      
    - name: Commit
      run: |
        git config --global user.name 'bit in that'
        git config --global user.email 'timothy.gummer@gmail.com'
        git add .
        git pull
        git commit -m 'ACTION: increment round number' || echo "No changes to commit"
        git pull
        git push 
