on:
  workflow_dispatch:

name: test locale
# Render quarto (including R code execution) and publish site to netlify 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        run: |
          locale -a 
          sudo locale-gen en_AU
          sudo locale-gen en_AU.utf8
          sudo update-locale 